
import DAO.AlmoxarifadoDAO;
import Dados.Almoxarifado;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author 277841
 */
public class CadAlmoxarifado extends javax.swing.JFrame {

    /**
     * Creates new form CadAlmoxarifado
     */
    public CadAlmoxarifado() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jlbTit = new javax.swing.JLabel();
        jlbCod = new javax.swing.JLabel();
        jlbNome = new javax.swing.JLabel();
        jtfCod_material = new javax.swing.JTextField();
        jtfNome_material = new javax.swing.JTextField();
        jlbEst = new javax.swing.JLabel();
        jtfEst_material = new javax.swing.JTextField();
        jlbRamo = new javax.swing.JLabel();
        jtfRamo_material = new javax.swing.JTextField();
        jlbLocal = new javax.swing.JLabel();
        jtfLocal_material = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtAlmoaxrifado = new javax.swing.JTable();
        jbPesq = new javax.swing.JButton();
        jbCad = new javax.swing.JButton();
        jbAtu = new javax.swing.JButton();
        jbLimpar = new javax.swing.JButton();
        jbSAIR = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(82, 127, 118));

        jlbTit.setFont(new java.awt.Font("Century Gothic", 3, 36)); // NOI18N
        jlbTit.setText("Almoxarifado ");

        jlbCod.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jlbCod.setText("Código:");

        jlbNome.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jlbNome.setText("Nome:");

        jtfCod_material.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N

        jtfNome_material.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N

        jlbEst.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jlbEst.setText("Estado:");

        jtfEst_material.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N

        jlbRamo.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jlbRamo.setText("Ramo:");

        jtfRamo_material.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N

        jlbLocal.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jlbLocal.setText("Local:");

        jtfLocal_material.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jtfLocal_material.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfLocal_materialActionPerformed(evt);
            }
        });

        jtAlmoaxrifado.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jtAlmoaxrifado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nome", "Ramo", "Estado", "Local"
            }
        ));
        jScrollPane1.setViewportView(jtAlmoaxrifado);

        jbPesq.setFont(new java.awt.Font("Century Gothic", 1, 15)); // NOI18N
        jbPesq.setText("Pesquisar");
        jbPesq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbPesqActionPerformed(evt);
            }
        });

        jbCad.setFont(new java.awt.Font("Century Gothic", 1, 15)); // NOI18N
        jbCad.setText("Cadastro");
        jbCad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCadActionPerformed(evt);
            }
        });

        jbAtu.setFont(new java.awt.Font("Century Gothic", 1, 15)); // NOI18N
        jbAtu.setText("Alterar");
        jbAtu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAtuActionPerformed(evt);
            }
        });

        jbLimpar.setFont(new java.awt.Font("Century Gothic", 1, 15)); // NOI18N
        jbLimpar.setText("Limpar");
        jbLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLimparActionPerformed(evt);
            }
        });

        jbSAIR.setFont(new java.awt.Font("Century Gothic", 1, 15)); // NOI18N
        jbSAIR.setText("SAIR");
        jbSAIR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSAIRActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbSAIR))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(133, 133, 133)
                                .addComponent(jlbTit)
                                .addGap(113, 113, 113))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jbCad)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jbPesq)
                                                .addGap(42, 42, 42))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                            .addComponent(jlbCod)
                                                            .addGap(18, 18, 18))
                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                            .addComponent(jlbNome)
                                                            .addGap(34, 34, 34)))
                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addComponent(jlbRamo)
                                                        .addGap(36, 36, 36)))
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jtfRamo_material, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jtfCod_material, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jtfNome_material, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addComponent(jbAtu)
                                                .addGap(49, 49, 49)
                                                .addComponent(jbLimpar))
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                    .addComponent(jlbEst)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                    .addComponent(jtfEst_material))
                                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                                    .addComponent(jlbLocal)
                                                    .addGap(18, 18, 18)
                                                    .addComponent(jtfLocal_material, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 37, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlbTit)
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbCod)
                    .addComponent(jtfCod_material, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlbEst)
                    .addComponent(jtfEst_material, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlbNome)
                            .addComponent(jtfNome_material, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtfRamo_material, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlbRamo)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlbLocal)
                            .addComponent(jtfLocal_material, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbLimpar)
                    .addComponent(jbCad)
                    .addComponent(jbAtu)
                    .addComponent(jbPesq))
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbSAIR)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtfLocal_materialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfLocal_materialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfLocal_materialActionPerformed

    private void jbSAIRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSAIRActionPerformed
      dispose();
    }//GEN-LAST:event_jbSAIRActionPerformed

    private void jbCadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCadActionPerformed
        Almoxarifado almox = new Almoxarifado();
       AlmoxarifadoDAO dao = new AlmoxarifadoDAO();

       almox.setcod_material(Integer.valueOf(jtfCod_material.getText()));
       almox.setnome_material(jtfNome_material.getText().trim());
       almox.setest_atual_material(jtfEst_material.getText().trim());
       almox.setramo_material(jtfRamo_material.getText().trim());
       almox.setlocal_material(jtfLocal_material.getText().trim());

        try {
            if(dao.inserir(almox)){
                JOptionPane.showMessageDialog(this, "Salvo");
            }
            else{
                JOptionPane.showMessageDialog(this, "Erro.\n", "Erro",JOptionPane.ERROR_MESSAGE);
            }
        } catch (SQLException ex) {
            Logger.getLogger(CadDIP.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jbCadActionPerformed

    private void jbPesqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbPesqActionPerformed
       DefaultTableModel modelo = new DefaultTableModel();
        
        modelo.addColumn("cod_material");
        modelo.addColumn("nome_material");
        modelo.addColumn("est_atual_material");
        modelo.addColumn("ramo_material");
        modelo.addColumn("local_material");
        
        AlmoxarifadoDAO almox = new AlmoxarifadoDAO();
        
        
         
         ArrayList<Almoxarifado>array = almox.buscarTodos();
         
         for(Almoxarifado j: array){
             System.out.println(j.getcod_material());
            
    
             Object[] dados={j.getcod_material(),j.getnome_material(),j.getest_atual_material(),j.getramo_material(),j.getlocal_material()};
             modelo.addRow(dados);
         }
         jtAlmoaxrifado.setModel(modelo);
    }//GEN-LAST:event_jbPesqActionPerformed

    private void jbAtuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAtuActionPerformed
       Almoxarifado almox = new Almoxarifado();
       AlmoxarifadoDAO dao = new AlmoxarifadoDAO ();
       
       almox.setcod_material(Integer.parseInt(jtfCod_material.getText()));
       almox.setnome_material(jtfNome_material.getText().trim());
       almox.setest_atual_material(jtfEst_material.getText().trim());
       almox.setramo_material(jtfRamo_material.getText().trim());
       almox.setlocal_material(jtfLocal_material.getText().trim());
       
       if(dao.alterar(almox)){
           JOptionPane.showMessageDialog(this, "Material alterado com Sucesso");
       }
       else{
           JOptionPane.showMessageDialog(this, "Erro  ao alterar o material.\n", "Erro", JOptionPane.ERROR_MESSAGE);
           
       }
       
       
    }//GEN-LAST:event_jbAtuActionPerformed

    private void jbLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLimparActionPerformed
       jtfNome_material.setText(null);
       jtfCod_material.setText(null);
       jtfEst_material.setText(null);
       jtfRamo_material.setText(null);
       jtfLocal_material.setText(null);
    }//GEN-LAST:event_jbLimparActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadAlmoxarifado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadAlmoxarifado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadAlmoxarifado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadAlmoxarifado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadAlmoxarifado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbAtu;
    private javax.swing.JButton jbCad;
    private javax.swing.JButton jbLimpar;
    private javax.swing.JButton jbPesq;
    private javax.swing.JButton jbSAIR;
    private javax.swing.JLabel jlbCod;
    private javax.swing.JLabel jlbEst;
    private javax.swing.JLabel jlbLocal;
    private javax.swing.JLabel jlbNome;
    private javax.swing.JLabel jlbRamo;
    private javax.swing.JLabel jlbTit;
    private javax.swing.JTable jtAlmoaxrifado;
    private javax.swing.JTextField jtfCod_material;
    private javax.swing.JTextField jtfEst_material;
    private javax.swing.JTextField jtfLocal_material;
    private javax.swing.JTextField jtfNome_material;
    private javax.swing.JTextField jtfRamo_material;
    // End of variables declaration//GEN-END:variables
}
