
import DAO.DIPDAO;
import Dados.DIP;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author 277841
 */
public class CadDIP extends javax.swing.JFrame {

    /**
     * Creates new form CadDIP
     */
    public CadDIP() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtDIP = new javax.swing.JTable();
        jlCodpt_dip = new javax.swing.JLabel();
        jtfCodpt_dip = new javax.swing.JTextField();
        jlPt_mt = new javax.swing.JLabel();
        jtfPt_mt = new javax.swing.JTextField();
        jlAtividade = new javax.swing.JLabel();
        jtfAtividade = new javax.swing.JTextField();
        jlPontuacao = new javax.swing.JLabel();
        jtfPontuacao = new javax.swing.JTextField();
        jlPont_ganha = new javax.swing.JLabel();
        jtfPont_ganha = new javax.swing.JTextField();
        jlData = new javax.swing.JLabel();
        jftfData = new javax.swing.JFormattedTextField();
        jbInserir = new javax.swing.JButton();
        jbLimpar = new javax.swing.JButton();
        jbVisualizar = new javax.swing.JButton();
        jbSair = new javax.swing.JButton();
        jbAtualizarSoma = new javax.swing.JButton();
        jlResul = new javax.swing.JLabel();
        jlTitulo = new javax.swing.JLabel();
        jtfResul = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(82, 127, 118));

        jtDIP.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jtDIP.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Patrulha", "Atividade", "Pontuação", "Pontuação ganha", "Data"
            }
        ));
        jScrollPane1.setViewportView(jtDIP);

        jlCodpt_dip.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jlCodpt_dip.setText("Código:");

        jtfCodpt_dip.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N

        jlPt_mt.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jlPt_mt.setText("Patrulha:");

        jtfPt_mt.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jtfPt_mt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfPt_mtActionPerformed(evt);
            }
        });

        jlAtividade.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jlAtividade.setText("Atividade:");

        jtfAtividade.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N

        jlPontuacao.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jlPontuacao.setText("Pontuação:");

        jtfPontuacao.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N

        jlPont_ganha.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jlPont_ganha.setText("Pontuação ganha:");

        jtfPont_ganha.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N

        jlData.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jlData.setText("Data:");

        try {
            jftfData.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("## / ## / ####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jbInserir.setFont(new java.awt.Font("Century Gothic", 1, 15)); // NOI18N
        jbInserir.setText("Inserir");
        jbInserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbInserirActionPerformed(evt);
            }
        });

        jbLimpar.setFont(new java.awt.Font("Century Gothic", 1, 15)); // NOI18N
        jbLimpar.setText("Limpar");
        jbLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLimparActionPerformed(evt);
            }
        });

        jbVisualizar.setFont(new java.awt.Font("Century Gothic", 1, 15)); // NOI18N
        jbVisualizar.setText("Visualizar");
        jbVisualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbVisualizarActionPerformed(evt);
            }
        });

        jbSair.setFont(new java.awt.Font("Century Gothic", 1, 15)); // NOI18N
        jbSair.setText("Sair");
        jbSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSairActionPerformed(evt);
            }
        });

        jbAtualizarSoma.setFont(new java.awt.Font("Century Gothic", 1, 15)); // NOI18N
        jbAtualizarSoma.setText("Atualizar");
        jbAtualizarSoma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAtualizarSomaActionPerformed(evt);
            }
        });

        jlResul.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jlResul.setText("Resultado:");

        jlTitulo.setFont(new java.awt.Font("Century Gothic", 3, 36)); // NOI18N
        jlTitulo.setText("DIP");

        jtfResul.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(158, 158, 158)
                .addComponent(jbVisualizar)
                .addGap(40, 40, 40)
                .addComponent(jbAtualizarSoma)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbLimpar)
                .addGap(56, 56, 56))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jtfAtividade, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlPt_mt)
                            .addComponent(jlCodpt_dip)
                            .addComponent(jlAtividade)
                            .addComponent(jlData))
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jtfPt_mt, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfCodpt_dip, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jftfData, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jlPontuacao)
                        .addGap(65, 65, 65)
                        .addComponent(jtfPontuacao, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlPont_ganha)
                            .addComponent(jlResul))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtfResul, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfPont_ganha, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 56, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(256, 256, 256)
                .addComponent(jlTitulo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jbInserir)
                        .addGap(492, 492, 492))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jbSair)
                        .addContainerGap())))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlTitulo)
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfCodpt_dip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlCodpt_dip)
                    .addComponent(jlPontuacao)
                    .addComponent(jtfPontuacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlPt_mt)
                    .addComponent(jtfPt_mt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlPont_ganha)
                    .addComponent(jtfPont_ganha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlAtividade)
                    .addComponent(jtfAtividade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfResul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlResul))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlData)
                    .addComponent(jftfData, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbInserir)
                    .addComponent(jbVisualizar)
                    .addComponent(jbAtualizarSoma)
                    .addComponent(jbLimpar))
                .addGap(32, 32, 32)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addComponent(jbSair)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbInserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbInserirActionPerformed
       DIP dip = new DIP();
       DIPDAO dao = new DIPDAO();
      
       
       dip.setpt_mt_dip(jtfPt_mt.getText().trim());
       dip.setatividade_dip(jtfAtividade.getText().trim());        
       dip.setdata_dip(jftfData.getText().trim());
       dip.setpont_dip(Integer.valueOf(jtfPontuacao.getText()));
       dip.setpont_ganha_dip(Integer.valueOf(jtfPont_ganha.getText()));
            
           
        try {
            if(dao.inserir(dip)){
                JOptionPane.showMessageDialog(this, "Salvo");
            }
            else{
                JOptionPane.showMessageDialog(this, "Erro.\n", "Erro",JOptionPane.ERROR_MESSAGE);
            }
        } catch (SQLException ex) {
            Logger.getLogger(CadDIP.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jbInserirActionPerformed
/**/
    private void jbVisualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbVisualizarActionPerformed
    
    
        DefaultTableModel modelo = new DefaultTableModel();
        
        modelo.addColumn("codpt_dip");
        modelo.addColumn("pt_mt_dip");
        modelo.addColumn("atividade_dip");
        modelo.addColumn("data_dip");
        modelo.addColumn("pont_dip");
        modelo.addColumn("pont_ganha_dip");
        
        
        
         
         DIPDAO dip = new DIPDAO();
         
         ArrayList<DIP>array = dip.buscarTodos();
         
         for(DIP j: array){
             System.out.println(j.getcodpt_dip());
             
             Object[] dados={j.getcodpt_dip(),j.getpt_mt_dip(),j.getatividade_dip(),j.getdata_dip(),j.getpont_dip(),j.getpont_ganha_dip()};
             modelo.addRow(dados);
         }
         jtDIP.setModel(modelo);
             
    }//GEN-LAST:event_jbVisualizarActionPerformed

    private void jbAtualizarSomaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAtualizarSomaActionPerformed
        double pont_ganha,nova_pont,resultado;
        String converter;
        pont_ganha=Double.valueOf(jtfPont_ganha.getText());
        nova_pont=Double.valueOf(jtfPont_ganha.getText());
        resultado=pont_ganha+nova_pont;
        converter=String.valueOf(resultado);
        jlResul.setText(converter);
        
        
        
        
    }//GEN-LAST:event_jbAtualizarSomaActionPerformed

    private void jbSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSairActionPerformed
    dispose();       
    }//GEN-LAST:event_jbSairActionPerformed

    private void jbLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLimparActionPerformed
         jtfCodpt_dip.setText(null);
        jtfPt_mt.setText(null);
        jtfAtividade.setText(null);
         jtfPontuacao.setText(null);
         jtfPont_ganha.setText(null);
         jftfData.setText(null);
    }//GEN-LAST:event_jbLimparActionPerformed

    private void jtfPt_mtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfPt_mtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfPt_mtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadDIP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadDIP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadDIP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadDIP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadDIP().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbAtualizarSoma;
    private javax.swing.JButton jbInserir;
    private javax.swing.JButton jbLimpar;
    private javax.swing.JButton jbSair;
    private javax.swing.JButton jbVisualizar;
    private javax.swing.JFormattedTextField jftfData;
    private javax.swing.JLabel jlAtividade;
    private javax.swing.JLabel jlCodpt_dip;
    private javax.swing.JLabel jlData;
    private javax.swing.JLabel jlPont_ganha;
    private javax.swing.JLabel jlPontuacao;
    private javax.swing.JLabel jlPt_mt;
    private javax.swing.JLabel jlResul;
    private javax.swing.JLabel jlTitulo;
    private javax.swing.JTable jtDIP;
    private javax.swing.JTextField jtfAtividade;
    private javax.swing.JTextField jtfCodpt_dip;
    private javax.swing.JTextField jtfPont_ganha;
    private javax.swing.JTextField jtfPontuacao;
    private javax.swing.JTextField jtfPt_mt;
    private javax.swing.JTextField jtfResul;
    // End of variables declaration//GEN-END:variables
}
