
import DAO.MensalidadeDAO;
import Dados.Mensalidade;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author 277841
 */
public class CadMensalidade extends javax.swing.JFrame {

    /**
     * Creates new form CadMensalidade
     */
    public CadMensalidade() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLtitulo = new javax.swing.JLabel();
        jlbCod_mens = new javax.swing.JLabel();
        jtfCod_mens = new javax.swing.JTextField();
        jlbMES_ANO = new javax.swing.JLabel();
        jftfMes_ano = new javax.swing.JFormattedTextField();
        jlbDATA_PAG = new javax.swing.JLabel();
        jftfData_pag = new javax.swing.JFormattedTextField();
        jlbSITUACAO = new javax.swing.JLabel();
        jtfSituacao = new javax.swing.JTextField();
        jlbATRASO = new javax.swing.JLabel();
        jtfAtraso = new javax.swing.JTextField();
        jlbRENOVACAO = new javax.swing.JLabel();
        jtfRenovacao = new javax.swing.JTextField();
        jbVisualizar = new javax.swing.JButton();
        jbSair = new javax.swing.JButton();
        jbAlterar = new javax.swing.JButton();
        jbLimpar = new javax.swing.JButton();
        jbInserir = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtMensalidade = new javax.swing.JTable();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(82, 127, 118));

        jLtitulo.setFont(new java.awt.Font("Century Gothic", 3, 36)); // NOI18N
        jLtitulo.setText("Mensalidade");

        jlbCod_mens.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jlbCod_mens.setText("Código:");

        jtfCod_mens.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N

        jlbMES_ANO.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jlbMES_ANO.setText("Mês/Ano:");

        try {
            jftfMes_ano.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jlbDATA_PAG.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jlbDATA_PAG.setText("Data Pagamento:");

        try {
            jftfData_pag.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jlbSITUACAO.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jlbSITUACAO.setText("Situação material:");

        jtfSituacao.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jtfSituacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfSituacaoActionPerformed(evt);
            }
        });

        jlbATRASO.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jlbATRASO.setText("Atraso:");

        jtfAtraso.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N

        jlbRENOVACAO.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jlbRENOVACAO.setText("Renovação:");

        jtfRenovacao.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N

        jbVisualizar.setFont(new java.awt.Font("Century Gothic", 1, 15)); // NOI18N
        jbVisualizar.setText("Visualizar");
        jbVisualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbVisualizarActionPerformed(evt);
            }
        });

        jbSair.setFont(new java.awt.Font("Century Gothic", 1, 15)); // NOI18N
        jbSair.setText("Sair");
        jbSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSairActionPerformed(evt);
            }
        });

        jbAlterar.setFont(new java.awt.Font("Century Gothic", 1, 15)); // NOI18N
        jbAlterar.setText("Alterar");
        jbAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAlterarActionPerformed(evt);
            }
        });

        jbLimpar.setFont(new java.awt.Font("Century Gothic", 1, 15)); // NOI18N
        jbLimpar.setText("Limpar");
        jbLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLimparActionPerformed(evt);
            }
        });

        jbInserir.setFont(new java.awt.Font("Century Gothic", 1, 15)); // NOI18N
        jbInserir.setText("Inserir");
        jbInserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbInserirActionPerformed(evt);
            }
        });

        jtMensalidade.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Mês/Ano", "Data de Pagamento", "Situação", "Renovação", "Atraso"
            }
        ));
        jScrollPane2.setViewportView(jtMensalidade);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(261, 261, 261)
                .addComponent(jlbSITUACAO)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jtfSituacao, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 50, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addComponent(jbAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jlbMES_ANO)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jftfMes_ano, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jbSair))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jlbCod_mens)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jtfCod_mens, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(182, 182, 182)
                                .addComponent(jLtitulo))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 507, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jbInserir)
                                        .addGap(195, 195, 195)
                                        .addComponent(jbVisualizar)
                                        .addGap(51, 51, 51)
                                        .addComponent(jbLimpar))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(262, 262, 262)
                                        .addComponent(jlbRENOVACAO)
                                        .addGap(18, 18, 18)
                                        .addComponent(jtfAtraso, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(jlbDATA_PAG)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jftfData_pag, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(82, 82, 82)
                                .addComponent(jlbATRASO)
                                .addGap(18, 18, 18)
                                .addComponent(jtfRenovacao, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLtitulo)
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbCod_mens)
                    .addComponent(jtfCod_mens, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlbSITUACAO)
                    .addComponent(jtfSituacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbMES_ANO)
                    .addComponent(jftfMes_ano, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfAtraso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlbRENOVACAO))
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbDATA_PAG)
                    .addComponent(jftfData_pag, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlbATRASO)
                    .addComponent(jtfRenovacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbAlterar)
                    .addComponent(jbInserir)
                    .addComponent(jbVisualizar)
                    .addComponent(jbLimpar))
                .addGap(28, 28, 28)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbSair)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtfSituacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfSituacaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfSituacaoActionPerformed

    private void jbVisualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbVisualizarActionPerformed
         DefaultTableModel modelo = new DefaultTableModel(); 
         
         modelo.addColumn("cod_mens");
         modelo.addColumn("mes_ano_mens");
         modelo.addColumn("data_pag_mens");
         modelo.addColumn("situacao_mens");
         modelo.addColumn("atraso_mens");
         modelo.addColumn("renovacao_mens");
         
         MensalidadeDAO mens = new MensalidadeDAO();
         ArrayList<Mensalidade>array = mens.buscarTodos();
         
         for(Mensalidade j: array){
             System.out.println(j.getcod_mens());
             
             Object[] dados={j.getcod_mens(), j.getmes_ano_mens(),j.getdata_pag_mens(),j.getsituacao_mens(),j.getatraso_mens(),j.getrenovacao_mens()};
             modelo.addRow(dados);
         }
         jtMensalidade.setModel(modelo);
             
         
         
         
                 
    }//GEN-LAST:event_jbVisualizarActionPerformed

    private void jbInserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbInserirActionPerformed
        Mensalidade mens = new Mensalidade();
            MensalidadeDAO dao = new MensalidadeDAO();
           
            mens.setcod_mens(Integer.valueOf(jtfCod_mens.getText()));        
            mens.setmes_ano_mens(jftfMes_ano.getText().trim());
            mens.setdata_pag_mens(jftfData_pag.getText().trim());
            mens.setsituacao_mens(jtfSituacao.getText().trim());
            mens.setatraso_mens(Integer.valueOf(jtfAtraso.getText()));
            mens.setrenovacao_mens(Double.valueOf(jtfRenovacao.getText()));
            
        try {
            if(dao.inserir(mens)){
                JOptionPane.showMessageDialog(this, "Salvo");
            }
            else{
                JOptionPane.showMessageDialog(this, "Erro.\n", "Erro",JOptionPane.ERROR_MESSAGE);
            }
        } catch (SQLException ex) {
            Logger.getLogger(CadMensalidade.class.getName()).log(Level.SEVERE, null, ex);
        }
            
            
    }//GEN-LAST:event_jbInserirActionPerformed

    private void jbAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAlterarActionPerformed
        Mensalidade mens = new Mensalidade();
            MensalidadeDAO dao = new MensalidadeDAO();
            
            mens.setcod_mens(Integer.valueOf(jtfCod_mens.getText()));     
            mens.setmes_ano_mens(jftfMes_ano.getText().trim());
            mens.setdata_pag_mens(jftfData_pag.getText().trim());
            mens.setsituacao_mens(jtfSituacao.getText().trim());
            mens.setatraso_mens(Integer.valueOf(jtfAtraso.getText()));
            mens.setrenovacao_mens(Double.valueOf(jtfRenovacao.getText()));
           
            if(dao.alterar(mens)){
                JOptionPane.showMessageDialog(this, "Alterado");
            }
            else{
                 JOptionPane.showMessageDialog(this, "Erro ao alterar.\n", "Erro",JOptionPane.ERROR_MESSAGE);
            }
            
    }//GEN-LAST:event_jbAlterarActionPerformed
/**/
    private void jbSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSairActionPerformed
        dispose();
    }//GEN-LAST:event_jbSairActionPerformed

    private void jbLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLimparActionPerformed
        jtfCod_mens.setText(null);
        jftfMes_ano.setText(null);
        jftfData_pag.setText(null);
         jtfSituacao.setText(null);
         jtfAtraso.setText(null);
         jtfRenovacao.setText(null);
    }//GEN-LAST:event_jbLimparActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadMensalidade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadMensalidade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadMensalidade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadMensalidade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadMensalidade().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLtitulo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton jbAlterar;
    private javax.swing.JButton jbInserir;
    private javax.swing.JButton jbLimpar;
    private javax.swing.JButton jbSair;
    private javax.swing.JButton jbVisualizar;
    private javax.swing.JFormattedTextField jftfData_pag;
    private javax.swing.JFormattedTextField jftfMes_ano;
    private javax.swing.JLabel jlbATRASO;
    private javax.swing.JLabel jlbCod_mens;
    private javax.swing.JLabel jlbDATA_PAG;
    private javax.swing.JLabel jlbMES_ANO;
    private javax.swing.JLabel jlbRENOVACAO;
    private javax.swing.JLabel jlbSITUACAO;
    private javax.swing.JTable jtMensalidade;
    private javax.swing.JTextField jtfAtraso;
    private javax.swing.JTextField jtfCod_mens;
    private javax.swing.JTextField jtfRenovacao;
    private javax.swing.JTextField jtfSituacao;
    // End of variables declaration//GEN-END:variables
}
