
import DAO.Membro_JuvenilDAO;
import Dados.Membro_Juvenil;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author 277841
 */
public class CadMembro_Juvenil extends javax.swing.JFrame {

    /**
     * Creates new form CadMembro_Juvenil
     */
    public CadMembro_Juvenil() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jbSair = new javax.swing.JButton();
        jbCad = new javax.swing.JButton();
        jbLimpar = new javax.swing.JButton();
        jbAlterar = new javax.swing.JButton();
        jlbTitulo = new javax.swing.JLabel();
        jbVisu = new javax.swing.JButton();
        jlbReg = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtMembro = new javax.swing.JTable();
        jlbNome = new javax.swing.JLabel();
        jlbRamo = new javax.swing.JLabel();
        jtfReg = new javax.swing.JTextField();
        jtfNome = new javax.swing.JTextField();
        jtfRamo = new javax.swing.JTextField();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(82, 127, 118));

        jbSair.setFont(new java.awt.Font("Century Gothic", 1, 15)); // NOI18N
        jbSair.setText("Sair");
        jbSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSairActionPerformed(evt);
            }
        });

        jbCad.setFont(new java.awt.Font("Century Gothic", 1, 15)); // NOI18N
        jbCad.setText("Cadastrar");
        jbCad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCadActionPerformed(evt);
            }
        });

        jbLimpar.setFont(new java.awt.Font("Century Gothic", 1, 15)); // NOI18N
        jbLimpar.setText("Limpar");
        jbLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLimparActionPerformed(evt);
            }
        });

        jbAlterar.setFont(new java.awt.Font("Century Gothic", 1, 15)); // NOI18N
        jbAlterar.setText("Alterar");
        jbAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAlterarActionPerformed(evt);
            }
        });

        jlbTitulo.setFont(new java.awt.Font("Century Gothic", 3, 36)); // NOI18N
        jlbTitulo.setText("Membro Juvenil");

        jbVisu.setFont(new java.awt.Font("Century Gothic", 1, 15)); // NOI18N
        jbVisu.setText("Visualizar");
        jbVisu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbVisuActionPerformed(evt);
            }
        });

        jlbReg.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jlbReg.setText("Registro:");

        jtMembro.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jtMembro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Registro", "Nome", "Ramo"
            }
        ));
        jScrollPane2.setViewportView(jtMembro);

        jlbNome.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jlbNome.setText("Nome:");

        jlbRamo.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jlbRamo.setText("Ramo:");

        jtfReg.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jtfReg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfRegActionPerformed(evt);
            }
        });

        jtfNome.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jtfNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfNomeActionPerformed(evt);
            }
        });

        jtfRamo.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jtfRamo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfRamoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbSair)
                .addGap(18, 18, 18))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 469, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jbCad)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jbLimpar))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jbAlterar)
                                .addGap(30, 30, 30)
                                .addComponent(jbVisu))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jlbNome)
                                        .addComponent(jlbReg)
                                        .addComponent(jlbRamo))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGap(20, 20, 20)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jtfNome, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jtfRamo, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGap(18, 18, 18)
                                            .addComponent(jtfReg, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addComponent(jlbTitulo)))))
                .addContainerGap(62, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jlbTitulo)
                .addGap(47, 47, 47)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbReg)
                    .addComponent(jtfReg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlbNome))
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbRamo)
                    .addComponent(jtfRamo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbCad)
                    .addComponent(jbAlterar)
                    .addComponent(jbVisu)
                    .addComponent(jbLimpar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jbSair)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtfNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfNomeActionPerformed

    private void jbSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSairActionPerformed
dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jbSairActionPerformed

    private void jbCadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCadActionPerformed
        
            Membro_Juvenil membroj = new Membro_Juvenil();
            
            Membro_JuvenilDAO dao = new Membro_JuvenilDAO();
            
            
            membroj.setreg_membro(Integer.valueOf(jtfReg.getText()));
            membroj.setnome_membro(jtfNome.getText().trim());
            membroj.setramo_membro(jtfRamo.getText().trim());
            
        try {
            if(dao.inserir(membroj)){
                JOptionPane.showMessageDialog(this,"Cadastrado com sucesso");
            }
            else{
                JOptionPane.showMessageDialog(this,"Erro ao cadastrar.\n","Erro",JOptionPane.ERROR_MESSAGE);
                
            }
// TODO add your handling code here:
        } catch (SQLException ex) {
            Logger.getLogger(CadMembro_Juvenil.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_jbCadActionPerformed

    private void jbLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLimparActionPerformed
        jtfReg.setText(null);
        jtfNome.setText(null);
        jtfRamo.setText(null);       
    }//GEN-LAST:event_jbLimparActionPerformed

    private void jbAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAlterarActionPerformed
Membro_Juvenil membroj = new Membro_Juvenil();

Membro_JuvenilDAO dao = new Membro_JuvenilDAO();

membroj.setreg_membro(Integer.valueOf(jtfReg.getText()));
membroj.setnome_membro(jtfNome.getText().trim());
membroj.setramo_membro(jtfRamo.getText().trim());

if(dao.alterar(membroj)){
    JOptionPane.showMessageDialog(this,"Alterado com sucesso");
}
else{
        JOptionPane.showMessageDialog(this,"Erro ao alterar.\n","Erro",JOptionPane.ERROR_MESSAGE);

}


// TODO add your handling code here:
    }//GEN-LAST:event_jbAlterarActionPerformed
/**/
    private void jbVisuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbVisuActionPerformed
DefaultTableModel modelo = new DefaultTableModel();

modelo.addColumn("Reg");
modelo.addColumn("Nome");
modelo.addColumn("Ramo");

Membro_JuvenilDAO membroj =new Membro_JuvenilDAO();

ArrayList<Membro_Juvenil>array = membroj.buscarTodos();

for(Membro_Juvenil j : array){
    
    System.out.println(j.getnome_membro());
    
    Object[] dados={j.getreg_membro(),j.getnome_membro(),j.getramo_membro()};
    modelo.addRow(dados);

    modelo.addRow(dados);
}
    jtMembro.setModel(modelo);
        // TODO add your handling code here:
    }//GEN-LAST:event_jbVisuActionPerformed

    private void jtfRegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfRegActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfRegActionPerformed

    private void jtfRamoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfRamoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfRamoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadMembro_Juvenil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadMembro_Juvenil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadMembro_Juvenil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadMembro_Juvenil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadMembro_Juvenil().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton jbAlterar;
    private javax.swing.JButton jbCad;
    private javax.swing.JButton jbLimpar;
    private javax.swing.JButton jbSair;
    private javax.swing.JButton jbVisu;
    private javax.swing.JLabel jlbNome;
    private javax.swing.JLabel jlbRamo;
    private javax.swing.JLabel jlbReg;
    private javax.swing.JLabel jlbTitulo;
    private javax.swing.JTable jtMembro;
    private javax.swing.JTextField jtfNome;
    private javax.swing.JTextField jtfRamo;
    private javax.swing.JTextField jtfReg;
    // End of variables declaration//GEN-END:variables
}

